version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_pedidos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_pedidos
    ports:
      - "3301j:3301j"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: ./backend
    container_name: api_pedidos
    restart: always
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
    working_dir: /app
    volumes:
      - ./backend:/app

volumes:
  mysql_data:
