services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sistema_pedidos
    ports:
      - 33061:3306
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
